- id: commitlint
  name: commitlint
  description: "commitlint for conventional commit message"
  entry: commitlint --file
  language: python
  stages: [commit-msg]
  args: [--header-max-length=72]  # Default value, can be overridden
